services:
  - type: web
    name: bodax-masters-discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: DISCORD_ADMIN_CHANNEL_ID
        sync: false
      - key: DISCORD_TICKET_CATEGORY_ID
        sync: false
      - key: DISCORD_SUPPORT_ROLE_ID
        sync: false
      - key: DISCORD_TICKET_CHANNEL_ID
        sync: false 